FIADatabase/FIADatabase/Areas/FIANCFiles/Controllers/HVIsController.cs
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using FIADatabase.Areas.FIANCFiles.Modules;
using FIADatabase.Contexts;
using Syncfusion.EJ2.RichTextEditor;

namespace FIADatabase.Areas.FIANCFiles.Controllers
{
    public class HVIsController : Controller
    {
        private FIANCFilesContext db = new FIANCFilesContext();

        // GET: FIANCFiles/HVIs
        [Authorize]
        public ActionResult Index()
        {
            return View(db.HVIs.OrderBy(s => s.lastName).ToList());
        }

        // GET: FIANCFiles/HVIs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HVI hVI = db.HVIs.Find(id);
            if (hVI == null)
            {
                return HttpNotFound();
            }
            return View(hVI);
        }

        // GET: FIANCFiles/HVIs/Create
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        // POST: FIANCFiles/HVIs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "HVIId,Portrait,lastName,firstName,Alias,DateofBirth,Bio")] HVI hVI, HttpPostedFileBase file1)
        {
            if (file1 != null)
            {
                hVI.Portrait = ImageToByteArray(file1);
            }
            if (ModelState.IsValid)
            {
                db.HVIs.Add(hVI);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(hVI);
        }

        // GET: FIANCFiles/HVIs/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HVI hVI = db.HVIs.Find(id);
            if (hVI == null)
            {
                return HttpNotFound();
            }
            return View(hVI);
        }

        // POST: FIANCFiles/HVIs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "HVIId,Portrait,lastName,firstName,Alias,DateofBirth,Bio")] HVI hVI, HttpPostedFileBase file1)
        {
            if (file1 != null)
            {
                hVI.Portrait = ImageToByteArray(file1);
            }
            if (ModelState.IsValid)
            {
                db.Entry(hVI).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(hVI);
        }

        // GET: FIANCFiles/HVIs/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HVI hVI = db.HVIs.Find(id);
            if (hVI == null)
            {
                return HttpNotFound();
            }
            return View(hVI);
        }

        // POST: FIANCFiles/HVIs/Delete/5
        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            HVI hVI = db.HVIs.Find(id);
            db.HVIs.Remove(hVI);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Signout()
        {
            FormsAuthentication.SignOut();
            return Redirect("/Home/Index");
        }

        public byte[] ImageToByteArray(HttpPostedFileBase imageIn)
        {
            MemoryStream target = new MemoryStream();
            imageIn.InputStream.CopyTo(target);
            byte[] bytes = target.ToArray();
            return bytes;
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FIADatabase/FIADatabase/Areas/FIANCFiles/Views/HVIs/Create.cshtml
@model FIADatabase.Areas.FIANCFiles.Modules.HVI

@{
    ViewBag.Title = "Create";
}

<h2 class="FIAh2 FIAText center">Create</h2>

@using (Html.BeginForm("Create", "HVIs", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4 class="FIAh3 FIAText center">HVI</h4>
        <hr class="FIAText"/>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group centered-div center">
            @Html.LabelFor(model => model.Portrait, htmlAttributes: new { @class = "control-label col-md-2 FIAText FIAp margins center" })
            <div class="col-md-10">
                <input type="file" name="file1" id="file1" />
                @Html.ValidationMessageFor(model => model.Portrait, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group centered-div">
            @Html.LabelFor(model => model.lastName, htmlAttributes: new { @class = "control-label col-md-2 FIAText FIAp margins width center" })
            <div class="col-md-10 cyber-input ac-red fg-black">
                @Html.EditorFor(model => model.lastName, new { htmlAttributes = new { @class = "FIAText" } })
                @Html.ValidationMessageFor(model => model.lastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group centered-div">
            @Html.LabelFor(model => model.firstName, htmlAttributes: new { @class = "control-label col-md-2 FIAText FIAp margins width center" })
            <div class="col-md-10 cyber-input ac-red fg-black">
                @Html.EditorFor(model => model.firstName, new { htmlAttributes = new { @class = "FIAText" } })
                @Html.ValidationMessageFor(model => model.firstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group centered-div">
            @Html.LabelFor(model => model.Alias, htmlAttributes: new { @class = "control-label col-md-2 FIAText FIAp margins width center" })
            <div class="col-md-10 cyber-input ac-red fg-black">
                @Html.EditorFor(model => model.Alias, new { htmlAttributes = new { @class = "FIAText" } })
                @Html.ValidationMessageFor(model => model.Alias, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group centered-div">
            @Html.LabelFor(model => model.DateofBirth, htmlAttributes: new { @class = "control-label col-md-2 FIAText FIAp margins width center" })
            <div class="col-md-10 cyber-input ac-red fg-black">
                @Html.EditorFor(model => model.DateofBirth, new { htmlAttributes = new { @class = "FIAText", @id = "datetime" } })
                @Html.ValidationMessageFor(model => model.DateofBirth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Bio, htmlAttributes: new { @class = "control-label col-md-2 FIAText FIAp margins center width" })
            <div class="col-md-10 margin-left textBox">
                @Html.EJS().RichTextEditorFor(model => model.Bio).Render()
                @Html.ValidationMessageFor(model => model.Bio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10 submit-button cyber-glitch-2">
                <div class="cyber-button-small">
                    <input type="submit" value="Create" class="btn btn-default cyber-input FIAText" />
                </div>
            </div>
        </div>
    </div>
}

<div class = "cyber-button-small blue-button back-button cyber-glitch-2">
    @Html.ActionLink("Back to List", "Index", new { @class="FIAText" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        $(document).ready(function () {
            $('#datetime').datetimepicker({
                monthsNames: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
                format: 'F j, Y',
                viewMode: "months",
                timepicker: false,
            });
        });
    </script>
}

FIADatabase/FIADatabase/Areas/FIANCFiles/Views/HVIs/Delete.cshtml
@model FIADatabase.Areas.FIANCFiles.Modules.HVI

@{
    ViewBag.Title = "Delete";
}

<h2 class="FIAText FIAh2 center">Delete</h2>

<h3 class="FIAText FIAh3 center">Are you sure you want to delete this?</h3>
<div>
    <h4 class="FIAText FIAh3 center">HVI</h4>
    <hr class="FIAText" />
    <dl class="dl-horizontal">
        @if (Model.Portrait != null)
        {
            <dd>
                <img class="portrait" src="data:image;base64, @System.Convert.ToBase64String(Model.Portrait)" />
            </dd>
        }

        @if (Model.Alias != null)
        {
            <dd class="FIAText FIAh2 center">
                @Html.DisplayFor(model => model.firstName) "@Html.DisplayFor(model => model.Alias)" @Html.DisplayFor(model => model.lastName)
            </dd>
        }
        else
        {
            <dd class="FIAText FIAh2 center">
                @Html.DisplayFor(model => model.firstName) @Html.DisplayFor(model => model.lastName)
            </dd>
        }

        <dt class="FIAText FIAp textBox">
            @Html.DisplayNameFor(model => model.DateofBirth): @Html.DisplayFor(model => model.DateofBirth)
        </dt>

        <dd class="FIAText FIAp textBox">
            @Html.Raw(Model.Bio)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color cyber-button-small back-button cyber-glitch-2">
            <input type="submit" value="Delete" class="btn btn-default FIAText" /> 
        </div>
        <div class="form-actions no-color cyber-button-small blue-button back-button cyber-glitch-2">
            @Html.ActionLink("Back to List", "Index")
        </div>
        
    }
</div>

FIADatabase/FIADatabase/Areas/FIANCFiles/Views/HVIs/Details.cshtml
@model FIADatabase.Areas.FIANCFiles.Modules.HVI

@if (Model.Alias != null)
{

    ViewBag.Title = Model.firstName + " \"" + Model.Alias + "\" " + Model.lastName;

}
else
{
    ViewBag.Title = Model.firstName + " " + Model.lastName;
}

@{
    bool isLoggedIn = true;
    if (string.IsNullOrWhiteSpace(User.Identity.Name))
    {
        isLoggedIn = false;
    }
}

<div>
    <dl class="dl-horizontal">
        @if (Model.Portrait != null)
        {

            <dd>
                <img class="portrait" src="data:image;base64, @System.Convert.ToBase64String(Model.Portrait)" />
            </dd>
        }

        @if (Model.Alias != null)
        {
            <dd class="FIAText FIAh2 center">
                @Html.DisplayFor(model => model.firstName) "@Html.DisplayFor(model => model.Alias)" @Html.DisplayFor(model => model.lastName)
            </dd>
        }
        else
        {
            <dd class="FIAText FIAh2 center">
                @Html.DisplayFor(model => model.firstName) @Html.DisplayFor(model => model.lastName)
            </dd>
        }


        <dt class="FIAText FIAp textBox">
            @Html.DisplayNameFor(model => model.DateofBirth): @Html.DisplayFor(model => model.DateofBirth)
        </dt>

        <dd class="FIAText FIAp textBox">
            @Html.Raw(Model.Bio)
        </dd>

    </dl>
</div>
<p>
    @{
        if (isLoggedIn)
        {
            <div class="cyber-button-small back-button center">
                @Html.ActionLink("Edit ", "Edit", new { id = Model.HVIId })
            </div>
        }
    }

    <div class="cyber-button-small blue-button back-button center">
        @Html.ActionLink("Back to List", "Index")
    </div>

</p>

FIADatabase/FIADatabase/Areas/FIANCFiles/Views/HVIs/Edit.cshtml
@model FIADatabase.Areas.FIANCFiles.Modules.HVI

@{
    ViewBag.Title = "Edit";
}

<h2 class="FIAText FIAh2 center">Edit</h2>

@using (Html.BeginForm("Edit", "HVIs", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4 class="FIAh3 FIAText center">HVI</h4>
        <hr class="FIAText"/>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.HVIId)

        <div class="form-group centered-div">
            @Html.LabelFor(model => model.Portrait, htmlAttributes: new { @class = "control-label col-md-2 FIAText FIAp margins" })
            <div class="col-md-10">
                @if (Model.Portrait != null)
                {
                    <img src="data:image;base64, @System.Convert.ToBase64String(Model.Portrait)" class="portrait"/>
                }
                <input type="file" name="file1" id="file1" />
                @Html.HiddenFor(model => model.Portrait)
                @Html.ValidationMessageFor(model => model.Portrait, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group centered-div">
            @Html.LabelFor(model => model.lastName, htmlAttributes: new { @class = "control-label col-md-2 FIAText FIAp margins width" })
            <div class="col-md-10 cyber-input ac-red fg-black">
                @Html.EditorFor(model => model.lastName, new { htmlAttributes = new { @class = "FIAText" } })
                @Html.ValidationMessageFor(model => model.lastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group centered-div">
            @Html.LabelFor(model => model.firstName, htmlAttributes: new { @class = "control-label col-md-2 FIAText FIAp margins width" })
            <div class="col-md-10 cyber-input ac-red fg-black">
                @Html.EditorFor(model => model.firstName, new { htmlAttributes = new { @class = "FIAText" } })
                @Html.ValidationMessageFor(model => model.firstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group centered-div">
            @Html.LabelFor(model => model.Alias, htmlAttributes: new { @class = "control-label col-md-2 FIAText FIAp margins width" })
            <div class="col-md-10 cyber-input ac-red fg-black">
                @Html.EditorFor(model => model.Alias, new { htmlAttributes = new { @class = "FIAText" } })
                @Html.ValidationMessageFor(model => model.Alias, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group centered-div">
            @Html.LabelFor(model => model.DateofBirth, htmlAttributes: new { @class = "control-label col-md-2 FIAText FIAp margins width" })
            <div class="col-md-10 cyber-input ac-red fg-black">
                @Html.EditorFor(model => model.DateofBirth, new { htmlAttributes = new { @class = "FIAText" } })
                @Html.ValidationMessageFor(model => model.DateofBirth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Bio, htmlAttributes: new { @class = "control-label col-md-2 FIAText FIAp margins width center" })
            <div class="col-md-10 margin-left textBox">
                @Html.EJS().RichTextEditorFor(model => model.Bio).Render()
                @Html.ValidationMessageFor(model => model.Bio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10 submit-button cyber-glitch-2">
                <div class="cyber-button-small">
                    <input type="submit" value="Save" class="btn btn-default cyber-input FIAText" />
                </div>
            </div>
        </div>
    </div>
}

<div class="cyber-button-small blue-button back-button cyber-glitch-2">
    @Html.ActionLink("Back to List", "Index", new { @class = "FIAText" })
</div>

FIADatabase/FIADatabase/Areas/FIANCFiles/Views/HVIs/Index.cshtml
@model IEnumerable<FIADatabase.Areas.FIANCFiles.Modules.HVI>

@{
    ViewBag.Title = "HVIs";
}

@{
    bool isLoggedIn = true;
    if (string.IsNullOrWhiteSpace(User.Identity.Name))
    {
        isLoggedIn = false;
    }
}

<h2 class="FIAText FIAh2 center">HVIs</h2>

@{
    if (isLoggedIn)
    {
    <p class="cyber-button-small blue-button back-button cyber-glitch-2">
        @Html.ActionLink("Create New", "Create")
    </p>
    }
}

<table class="table no-border">
    @foreach (var item in Model)
    {
        <tr>
            <td class="cyber-button-small wide blue-button back-button">
                <a href=@Url.Action("Details", new { id = item.HVIId })>
                @if (item.Alias != null)
                {
                    <p>@Html.DisplayFor(modelItem => item.firstName) "@Html.DisplayFor(modelItem => item.Alias)" @Html.DisplayFor(modelItem => item.lastName)</p>
                }
                else
                {
                    <p>@Html.DisplayFor(modelItem => item.firstName) @Html.DisplayFor(modelItem => item.lastName)</p>
                }
                </a>
            </td>

            @{
                if (isLoggedIn)
                {
                    <td class="cyber-button-small back-button center">
                        @Html.ActionLink("Edit ", "Edit", new { id = item.HVIId })
                    </td>
                    <td class="cyber-button-small back-button center" center>
                        @Html.ActionLink("Delete ", "Delete", new { id = item.HVIId })
                    </td>
                }
            }
        </tr>
    }
</table>