FIADatabase/FIADatabase/Areas/FIANCFiles/Controllers/InterludesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using FIADatabase.Areas.FIANCFiles.Modules;
using FIADatabase.Contexts;
using FIADatabase.Migrations;

namespace FIADatabase.Areas.FIANCFiles.Controllers
{
    public class InterludesController : Controller
    {
        private FIANCFilesContext db = new FIANCFilesContext();

        // GET: FIANCFiles/Interludes
        public ActionResult Index()
        {
            return View(db.Interludes.OrderBy(s => s.orderNumber).ToList());
        }

        // GET: FIANCFiles/Interludes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Interlude interlude = db.Interludes.Find(id);
            if (interlude == null)
            {
                return HttpNotFound();
            }
            return View(interlude);
        }

        // GET: FIANCFiles/Interludes/Create
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        // POST: FIANCFiles/Interludes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "interludeId,orderNumber,Title,areaMap,districtMap,bureauMap,localMap,Briefing,Video,AAR")] Interlude interlude,
            HttpPostedFileBase file1, HttpPostedFileBase file2, HttpPostedFileBase file3, HttpPostedFileBase file4)
        {
            if (file1 != null)
            {
                interlude.areaMap = ImageToByteArray(file1);
            }
            if (file2 != null)
            {
                interlude.districtMap = ImageToByteArray(file2);
            }
            if (file3 != null)
            {
                interlude.bureauMap = ImageToByteArray(file3);
            }
            if (file4 != null)
            {
                interlude.localMap = ImageToByteArray(file4);
            }
            if (ModelState.IsValid)
            {
                db.Interludes.Add(interlude);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(interlude);
        }

        // GET: FIANCFiles/Interludes/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Interlude interlude = db.Interludes.Find(id);
            if (interlude == null)
            {
                return HttpNotFound();
            }
            return View(interlude);
        }

        // POST: FIANCFiles/Interludes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "interludeId,orderNumber,Title,areaMap,districtMap,bureauMap,localMap,Briefing,Video,AAR")] Interlude interlude,
            HttpPostedFileBase file1, HttpPostedFileBase file2, HttpPostedFileBase file3, HttpPostedFileBase file4)
        {
            if (file1 != null)
            {
                interlude.areaMap = ImageToByteArray(file1);
            }
            if (file2 != null)
            {
                interlude.districtMap = ImageToByteArray(file2);
            }
            if (file3 != null)
            {
                interlude.bureauMap = ImageToByteArray(file3);
            }
            if (file4 != null)
            {
                interlude.localMap = ImageToByteArray(file4);
            }
            if (ModelState.IsValid)
            {
                db.Entry(interlude).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(interlude);
        }

        // GET: FIANCFiles/Interludes/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Interlude interlude = db.Interludes.Find(id);
            if (interlude == null)
            {
                return HttpNotFound();
            }
            return View(interlude);
        }

        // POST: FIANCFiles/Interludes/Delete/5
        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Interlude interlude = db.Interludes.Find(id);
            db.Interludes.Remove(interlude);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public byte[] ImageToByteArray(HttpPostedFileBase imageIn)
        {
            MemoryStream target = new MemoryStream();
            imageIn.InputStream.CopyTo(target);
            byte[] bytes = target.ToArray();
            return bytes;
        }

        public ActionResult Signout()
        {
            FormsAuthentication.SignOut();
            return Redirect("/Home/Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FIADatabase/FIADatabase/Areas/FIANCFiles/Views/Interludes/Create.cshtml
@model FIADatabase.Areas.FIANCFiles.Modules.Interlude

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/FIANCFiles/Views/Shared/_Layout.cshtml";
}

<h2 class="FIAh2 FIAText center">Create</h2>

@using (Html.BeginForm("Create", "Interludes", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4 class="FIAh3 FIAText center">Interlude</h4>
        <hr class="FIAText" />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group centered-div">
            @Html.LabelFor(model => model.orderNumber, htmlAttributes: new { @class = "control-label col-md-2 FIAText FIAp margins wide center" })
            <div class="col-md-10 cyber-input ac-red fg-black">
                @Html.EditorFor(model => model.orderNumber, new { htmlAttributes = new { @class = "FIAText" } })
                @Html.ValidationMessageFor(model => model.orderNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group centered-div">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2 FIAText FIAp margins center width" })
            <div class="col-md-10 cyber-input ac-red fg-black">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "FIAText" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group centered-div">
            @Html.LabelFor(model => model.areaMap, htmlAttributes: new { @class = "control-label col-md-2 FIAText FIAp margins wide center" })
            <div class="col-md-10">
                <input type="file" name="file1" id="file1" />
                @Html.ValidationMessageFor(model => model.areaMap, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group centered-div">
            @Html.LabelFor(model => model.districtMap, htmlAttributes: new { @class = "control-label col-md-2 FIAText FIAp margins wide center" })
            <div class="col-md-10">
                <input type="file" name="file2" id="file2" />
                @Html.ValidationMessageFor(model => model.districtMap, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group centered-div">
            @Html.LabelFor(model => model.bureauMap, htmlAttributes: new { @class = "control-label col-md-2 FIAText FIAp margins wide center" })
            <div class="col-md-10">
                <input type="file" name="file3" id="file3" />
                @Html.ValidationMessageFor(model => model.bureauMap, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group centered-div">
            @Html.LabelFor(model => model.localMap, htmlAttributes: new { @class = "control-label col-md-2 FIAText FIAp margins wide center" })
            <div class="col-md-10">
                <input type="file" name="file4" id="file4" />
                @Html.ValidationMessageFor(model => model.localMap, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Briefing, htmlAttributes: new { @class = "control-label col-md-2 FIAText FIAp margins center width" })
            <div class="col-md-10 margin-left textBox">
                @Html.EJS().RichTextEditorFor(model => model.Briefing).Render()
                @Html.ValidationMessageFor(model => model.Briefing, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group centered-div">
            @Html.LabelFor(model => model.Video, htmlAttributes: new { @class = "control-label col-md-2 FIAText FIAp margins center width" })
            <div class="col-md-10 cyber-input ac-red fg-black">
                @Html.EditorFor(model => model.Video, new { htmlAttributes = new { @class = "FIAText" } })
                @Html.ValidationMessageFor(model => model.Video, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AAR, htmlAttributes: new { @class = "control-label col-md-2 FIAText FIAp margins center width" })
            <div class="col-md-10 margin-left textBox">
                @Html.EJS().RichTextEditorFor(model => model.AAR).Render()
                @Html.ValidationMessageFor(model => model.AAR, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10 submit-button cyber-glitch-2">
                <div class="cyber-button-small">
                    <input type="submit" value="Create" class="btn btn-default cyber-input FIAText" />
                </div>
            </div>
        </div>
    </div>
}

<div class="cyber-button-small blue-button back-button cyber-glitch-2">
    @Html.ActionLink("Back to List", "Index", new { @class = "FIAText" })
</div>

FIADatabase/FIADatabase/Areas/FIANCFiles/Views/Interludes/Delete.cshtml
@model FIADatabase.Areas.FIANCFiles.Modules.Interlude

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/FIANCFiles/Views/Shared/_Layout.cshtml";
}

<h2 class="FIAText FIAh2 center">Delete</h2>

<h3 class="FIAText FIAh3 center">Are you sure you want to delete this?</h3>
<div>
    <h4 class="FIAText FIAh4 center">Interlude</h4>
    <hr class="FIAText" />
    <dl class="dl-horizontal">
        <dt class="FIAText FIAp center">
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd class="FIAText FIAp center">
            @Html.DisplayFor(model => model.Title)
        </dd>
        @if (Model.areaMap != null)
        {
            <dt class="FIAText FIAh2 center">@Html.DisplayNameFor(model => model.areaMap)</dt>

            <dd>
                <img src="data:image;base64, @System.Convert.ToBase64String(Model.areaMap)" class="map" />
            </dd>
        }

        @if (Model.districtMap != null)
        {
            <dt class="FIAText FIAp center">@Html.DisplayNameFor(model => model.districtMap)</dt>

            <dd>
                <img src="data:image;base64, @System.Convert.ToBase64String(Model.districtMap)" class="map" />
            </dd>
        }
        @if (Model.bureauMap != null)
        {
            <dt class="FIAText FIAp center">@Html.DisplayNameFor(model => model.bureauMap)</dt>

            <dd>
                <img src="data:image;base64, @System.Convert.ToBase64String(Model.bureauMap)" class="map" />
            </dd>
        }
        @if (Model.localMap != null)
        {
            <dt class="FIAText FIAp center">@Html.DisplayNameFor(model => model.localMap)</dt>

            <dd>
                <img src="data:image;base64, @System.Convert.ToBase64String(Model.localMap)" class="map" />
            </dd>
        }
        <dt class="FIAText FIAp center">
            @Html.DisplayNameFor(model => model.Briefing)
        </dt>

        <dd class="FIAText FIAp textBox">
            @Html.Raw(Model.Briefing)
        </dd>

        <dt class="FIAText FIAp center">
            @Html.DisplayNameFor(model => model.Video)
        </dt>

        <dd class="center">
            <iframe crossorigin='anonymous' width="560" height="315" src="@Html.DisplayFor(model => model.Video)" title="YouTube video player" frameborder="0"
                    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
        </dd>

        <dt class="FIAText FIAp center">
            @Html.DisplayNameFor(model => model.AAR)
        </dt>

        <dd class="FIAText FIAp textBox">
            @Html.Raw(Model.AAR)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10 submit-button cyber-glitch-2">
                <div class="cyber-button-small">
                    <input type="submit" value="Delete" class="btn btn-default cyber-input FIAText" />
                </div>
            </div>
        </div>

        <div class="cyber-button-small blue-button back-button center">
            @Html.ActionLink("Back to List", "Index")
        </div>
    }

FIADatabase/FIADatabase/Areas/FIANCFiles/Views/Interludes/Details.cshtml
@model FIADatabase.Areas.FIANCFiles.Modules.Interlude
@using FIADatabase.Areas.FIANCFiles.Modules;
@using FIADatabase.Contexts;

@functions
{
    private FIANCFilesContext db = new FIANCFilesContext();

}

@{
    bool isLoggedIn = true;
    if (string.IsNullOrWhiteSpace(User.Identity.Name))
    {
        isLoggedIn = false;
    }

    bool hasNext = db.Interludes.Any(s => s.orderNumber == Model.orderNumber + 1);
    bool hasPrev = db.Interludes.Any(s => s.orderNumber == Model.orderNumber - 1);
}

@{
    int numPics = 0;
    if (Model.areaMap != null)
    {
        numPics += 1;
    }
    if (Model.districtMap != null)
    {
        numPics += 1;
    }
    if (Model.bureauMap != null)
    {
        numPics += 1;
    }
    if (Model.localMap != null)
    {
        numPics += 1;
    }
}

@{
    ViewBag.Title = Model.Title;
    Layout = "~/Areas/FIANCFiles/Views/Shared/_Layout.cshtml";
}

<div>
    <dl class="dl-horizontal">
        <div class="FIAText FIAh2 center">
            @Html.DisplayFor(model => model.Title)
        </div>
        <dd>
            <div class="slideshow-container">
                @if (Model.areaMap != null)
                {
                    <div class="mySlides">
                        <img class="map" src="data:image;base64, @System.Convert.ToBase64String(Model.areaMap)" />
                    </div>
                }

                @if (Model.districtMap != null)
                {
                    <div class="mySlides">
                        <img class="map" src="data:image;base64, @System.Convert.ToBase64String(Model.districtMap)" />
                    </div>
                }
                @if (Model.bureauMap != null)
                {
                    <div class="mySlides">
                        <img class="map" src="data:image;base64, @System.Convert.ToBase64String(Model.bureauMap)" />
                    </div>
                }
                @if (Model.localMap != null)
                {
                    <div class="mySlides">
                        <img class="map" src="data:image;base64, @System.Convert.ToBase64String(Model.localMap)" />
                    </div>
                }
            </div>
            @if (numPics >= 2)
            {<div class="blue-button back-button cyber-glitch-2">
                    <a class="next cyber-button-small blue-button" onclick="plusSlides(1)">Click to Zoom</a>
                </div>

            }
            else
            {
                <a class="next" onclick="plusSlides(1)"></a>
            }
        </dd>

        <dd class="FIAText FIAp">
            @Html.Raw(Model.Briefing)
        </dd>

        @if (Model.Video != null)
        {
            <dd class="center">
                <iframe crossorigin='anonymous' width="560" height="315" src="@Html.DisplayFor(model => model.Video)" title="YouTube video player" frameborder="0"
                        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
            </dd>
        }

        <dd class="FIAText FIAp">
            @Html.Raw(Model.AAR)
        </dd>

    </dl>
</div>
<p>
    @{
        if (isLoggedIn)
        {
            <div class="cyber-button-small back-button center blue-button">
                @Html.ActionLink("Edit ", "Edit", new { id = Model.interludeId })
            </div>

        }
        if (hasPrev)
        {
            Interlude prev = db.Interludes.FirstOrDefault(s => s.orderNumber == Model.orderNumber - 1);
            <div class="cyber-button-small back-button center blue-button">
                @Html.ActionLink("Previous", "Details", new { id = prev.interludeId })
            </div>
        }
        if (hasNext)
        {
            Interlude next = db.Interludes.FirstOrDefault(s => s.orderNumber == Model.orderNumber + 1);
            <div class="cyber-button-small back-button center blue-button">
                @Html.ActionLink("Next", "Details", new { id = next.interludeId })
            </div>
        }
    }

    <div class="cyber-button-small back-button center">
        @Html.ActionLink("Back to List", "Index")
    </div>


</p>

@section Scripts
{
    <script type="text/javascript">
        let slideIndex = 1;
        showSlides(slideIndex);

        function plusSlides(n) {
            showSlides(slideIndex += n);
        }

        function currentSlide(n) {
            showSlides(slideIndex = n);
        }

        function showSlides(n) {
            let i;
            let slides = document.getElementsByClassName("mySlides");
            let dots = document.getElementsByClassName("mySlides");
            if (n > slides.length) { slideIndex = 1 }
            if (n < 1) { slideIndex = slides.length }
            for (i = 0; i < dots.length; i++) {
                slides[i].style.display = "none";
            }
            for (i = 0; i < dots.length; i++) {
                dots[i].className = dots[i].className.replace(" active", "");
            }
            slides[slideIndex - 1].style.display = "block";
            dots[slideIndex - 1].className += " active";
        }
    </script>
}

FIADatabase/FIADatabase/Areas/FIANCFiles/Views/Interludes/Edit.cshtml
@model FIADatabase.Areas.FIANCFiles.Modules.Interlude

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/FIANCFiles/Views/Shared/_Layout.cshtml";
}

<h2 class="FIAText FIAh2 center">Edit</h2>

@using (Html.BeginForm("Edit", "Interludes", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4 class="FIAh3 FIAText center">Interlude</h4>
        <hr class="FIAText" />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.interludeId)

        <div class="form-group centered-div">
            @Html.LabelFor(model => model.orderNumber, htmlAttributes: new { @class = "control-label col-md-2 FIAText FIAp margins width" })
            <div class="col-md-10 cyber-input ac-red fg-black">
                @Html.EditorFor(model => model.orderNumber, new { htmlAttributes = new { @class = "FIAText" } })
                @Html.ValidationMessageFor(model => model.orderNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group centered-div">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2 FIAText FIAp margins width" })
            <div class="col-md-10 cyber-input ac-red fg-black">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "FIAText" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.areaMap, htmlAttributes: new { @class = "control-label col-md-2 FIAText FIAp margins width center" })
            <div class="col-md-10">
                @if (Model.areaMap != null)
                {
                    <img src="data:image;base64, @System.Convert.ToBase64String(Model.areaMap)" class="map" />
                }
                <input type="file" name="file1" id="file1" class="center-input" />
                @Html.HiddenFor(model => model.areaMap)
                @Html.ValidationMessageFor(model => model.areaMap, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.districtMap, htmlAttributes: new { @class = "control-label col-md-2 FIAText FIAp margins width center" })
            <div class="col-md-10">
                @if (Model.districtMap != null)
                {
                    <img src="data:image;base64, @System.Convert.ToBase64String(Model.districtMap)" class="map" />
                }
                <input type="file" name="file2" id="file2" class="center-input" />
                @Html.HiddenFor(model => model.districtMap)
                @Html.ValidationMessageFor(model => model.districtMap, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.bureauMap, htmlAttributes: new { @class = "control-label col-md-2 FIAText FIAp margins width center" })
            <div class="col-md-10">
                @if (Model.bureauMap != null)
                {
                    <img src="data:image;base64, @System.Convert.ToBase64String(Model.bureauMap)" class="map" />
                }
                <input type="file" name="file3" id="file3" class="center-input" />
                @Html.HiddenFor(model => model.bureauMap)
                @Html.ValidationMessageFor(model => model.bureauMap, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.localMap, htmlAttributes: new { @class = "control-label col-md-2 FIAText FIAp margins width center" })
            <div class="col-md-10">
                @if (Model.localMap != null)
                {
                    <img src="data:image;base64, @System.Convert.ToBase64String(Model.localMap)" class="map" />
                }
                <input type="file" name="file4" id="file4" class="center-input" />
                @Html.HiddenFor(model => model.localMap)
                @Html.ValidationMessageFor(model => model.localMap, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Briefing, htmlAttributes: new { @class = "control-label col-md-2 FIAText FIAp margins width center" })
            <div class="col-md-10 textBox">
                @Html.EJS().RichTextEditorFor(model => model.Briefing).Render()
                @Html.ValidationMessageFor(model => model.Briefing, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group centered-div">
            @Html.LabelFor(model => model.Video, htmlAttributes: new { @class = "control-label col-md-2 FIAText FIAp margins width center" })
            <div class="col-md-10 cyber-input ac-red fg-black center">
                @Html.EditorFor(model => model.Video, new { htmlAttributes = new { @class = "FIAText" } })
                @Html.ValidationMessageFor(model => model.Video, "", new { @class = "text-danger" })
            </div>
            @if (Model.Video != null)
            {
                <iframe crossorigin='anonymous' width="560" height="315" src="@Html.DisplayFor(model => model.Video)" title="YouTube video player" frameborder="0"
                        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
            }
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AAR, htmlAttributes: new { @class = "control-label col-md-2 FIAText FIAp margins width center" })
            <div class="col-md-10 textBox">
                @Html.EJS().RichTextEditorFor(model => model.AAR).Render()
                @Html.ValidationMessageFor(model => model.AAR, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10 submit-button cyber-glitch-2">
                <div class="cyber-button-small">
                    <input type="submit" value="Save" class="btn btn-default cyber-input FIAText" />
                </div>
            </div>
        </div>
    </div>
}

<div class="cyber-button-small blue-button back-button cyber-glitch-2">
    @Html.ActionLink("Back to List", "Index", new { @class = "FIAText" })
</div>

FIADatabase/FIADatabase/Areas/FIANCFiles/Views/Interludes/Index.cshtml
@model IEnumerable<FIADatabase.Areas.FIANCFiles.Modules.Interlude>

@{
    ViewBag.Title = "Interlude";
    Layout = "~/Areas/FIANCFiles/Views/Shared/_Layout.cshtml";
}

@{
    bool isLoggedIn = true;
    if (string.IsNullOrWhiteSpace(User.Identity.Name))
    {
        isLoggedIn = false;
    }
}


<h2 class="FIAText FIAh2 center">Interlude</h2>

@if (isLoggedIn)
{
    <p class="cyber-button-small blue-button back-button cyber-glitch-2">
        @Html.ActionLink("Create New", "Create")
    </p>
}

<table class="table no-border">

    @foreach (var item in Model)
    {
        <tr>
            <td class="cyber-button-small wide blue-button back-button">
                <a href=@Url.Action("Details", new { id = item.interludeId})><p>@Html.DisplayFor(modelItem => item.Title)</p></a>
            </td>
            @{
                if (isLoggedIn)
                {
                    <td class="cyber-button-small back-button center">
                        @Html.ActionLink("Edit ", "Edit", new { id = item.interludeId })
                    </td>
                    <td class="cyber-button-small back-button center" center>
                        @Html.ActionLink("Delete ", "Delete", new { id = item.interludeId })
                    </td>
                }
            }
        </tr>
    }

</table>