FIADatabase/FIADatabase/Areas/FIANCFiles/Controllers/ActIsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using FIADatabase.Areas.FIANCFiles.Modules;
using FIADatabase.Contexts;
using FIADatabase.Migrations;
using ActI = FIADatabase.Areas.FIANCFiles.Modules.ActI;

namespace FIADatabase.Areas.FIANCFiles.Controllers
{
    public class ActIsController : Controller
    {
        private FIANCFilesContext db = new FIANCFilesContext();

        // GET: FIANCFiles/ActIs
        public ActionResult Index()
        {
            return View(db.ActIs.OrderBy(s => s.orderNumber).ToList());
        }

        // GET: FIANCFiles/ActIs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ActI actI = db.ActIs.Find(id);
            if (actI == null)
            {
                return HttpNotFound();
            }
            return View(actI);
        }

        // GET: FIANCFiles/ActIs/Create
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        // POST: FIANCFiles/ActIs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ActIId,orderNumber,Title,areaMap,districtMap,bureauMap,localMap,Briefing,Video,AAR")] ActI actI,
            HttpPostedFileBase file1, HttpPostedFileBase file2, HttpPostedFileBase file3, HttpPostedFileBase file4)
        {
            if (file1 != null)
            {
                actI.areaMap = ImageToByteArray(file1);
            }
            if (file2 != null)
            {
                actI.districtMap = ImageToByteArray(file2);
            }
            if (file3 != null)
            {
                actI.bureauMap = ImageToByteArray(file3);
            }
            if (file4 != null)
            {
                actI.localMap = ImageToByteArray(file4);
            }
            if (ModelState.IsValid)
            {
                db.ActIs.Add(actI);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(actI);
        }

        // GET: FIANCFiles/ActIs/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ActI actI = db.ActIs.Find(id);
            if (actI == null)
            {
                return HttpNotFound();
            }
            return View(actI);
        }

        // POST: FIANCFiles/ActIs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ActIId,orderNumber,Title,areaMap,districtMap,bureauMap,localMap,Briefing,Video,AAR")] ActI actI,
            HttpPostedFileBase file1, HttpPostedFileBase file2, HttpPostedFileBase file3, HttpPostedFileBase file4)
        {
            if (ModelState.IsValid)
            {
                if (file1 != null)
                {
                    actI.areaMap = ImageToByteArray(file1);
                }
                if (file2 != null)
                {
                    actI.districtMap = ImageToByteArray(file2);
                }
                if (file3 != null)
                {
                    actI.bureauMap = ImageToByteArray(file3);
                }
                if (file4 != null)
                {
                    actI.localMap = ImageToByteArray(file4);
                }
                db.Entry(actI).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(actI);
        }

        // GET: FIANCFiles/ActIs/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ActI actI = db.ActIs.Find(id);
            if (actI == null)
            {
                return HttpNotFound();
            }
            return View(actI);
        }

        // POST: FIANCFiles/ActIs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult DeleteConfirmed(int id)
        {
            ActI actI = db.ActIs.Find(id);
            db.ActIs.Remove(actI);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public byte[] ImageToByteArray(HttpPostedFileBase imageIn)
        {
            MemoryStream target = new MemoryStream();
            imageIn.InputStream.CopyTo(target);
            byte[] bytes = target.ToArray();
            return bytes;
        }

        public ActionResult Signout()
        {
            FormsAuthentication.SignOut();
            return Redirect("/Home/Index");
        }

        public ActionResult NCIndex()
        {
            return View();
        }
        public ActionResult Main()
        {
            return View();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FIADatabase/FIADatabase/Areas/FIANCFiles/Controllers/MainController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FIADatabase.Areas.FIANCFiles.Controllers
{
    public class MainController : Controller
    {
        // GET: FIANCFiles/Main
        public ActionResult Main()
        {
            return View();
        }

        public ActionResult NCIndex()
        {
            return View();
        }
    }
}

FIADatabase/FIADatabase/Areas/FIAUsers/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Runtime.InteropServices;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using System.Web.Security;
using FIADatabase.Areas.FIAUsers.Models;
using FIADatabase.Contexts;

namespace FIADatabase.Areas.FIAUsers.Controllers
{
    public class UsersController : Controller
    {
        private FIAUsersContext db = new FIAUsersContext();

        // GET: FIAUsers/Users
        [Authorize]
        public ActionResult Index()
        {
            return View(db.Users.ToList());
        }

        // GET: FIAUsers/Users/Details/5
        [Authorize]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // GET: FIAUsers/Users/Create
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        // POST: FIAUsers/Users/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "UserId,Username,Password,ConfirmPassword,Salt,HashedPassword")] User user)
        {
            if (ModelState.IsValid)
            {
                db.Configuration.ValidateOnSaveEnabled = false;
                user.Salt = Crypto.GenerateSalt();
                string password = user.Password + user.Salt;
                user.HashedPassword = Crypto.HashPassword(password);
                user.Password = "";
                user.ConfirmPassword = "";
                db.Users.Add(user);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(user);
        }

        // GET: FIAUsers/Users/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: FIAUsers/Users/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "UserId,Username,Password,ConfirmPassword,Salt,HashedPassword")] User user)
        {
            if (ModelState.IsValid)
            {
                db.Entry(user).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(user);
        }

        // GET: FIAUsers/Users/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: FIAUsers/Users/Delete/5
        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            User user = db.Users.Find(id);
            db.Users.Remove(user);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(User user, string returnUrl)
        {
            bool userExists = db.Users.Any(x => x.Username == user.Username);
            if (userExists) 
            {
                User u = db.Users.FirstOrDefault(x => x.Username == user.Username);
                string password = user.Password + u.Salt;
                bool userExist = Crypto.VerifyHashedPassword(u.HashedPassword, password);

                if (userExist)
                {
                    FormsAuthentication.SetAuthCookie(u.Username, false);
                    if (!string.IsNullOrEmpty(returnUrl))
                    {
                        return Redirect(returnUrl);
                    }
                    return Redirect("/Home/Index");
                }

                ModelState.AddModelError("", "Username or Password is incorrect.");

                return View();
            }

            ModelState.AddModelError("", "Username or Password is incorrect.");

            return View();

        }

        public ActionResult Signout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Login");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FIADatabase/FIADatabase/Areas/FIANCFiles/Views/Shared/_Layout.cshtml
@{
    bool isLoggedIn = true;
    if (string.IsNullOrWhiteSpace(User.Identity.Name))
    {
        isLoggedIn = false;
    }
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="~/Content/Images/seal.png" />
    <link rel="stylesheet" href="https://cdn.syncfusion.com/ej2/23.2.4/fluent.css" />
    <script src="https://cdn.syncfusion.com/ej2/23.2.4/dist/ej2.min.js"></script>
    <title>@ViewBag.Title - FIA Database</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body class="FIAbody">
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("FIA Database", "Index", "Home", new { area = "" }, new { @class = "navbar-brand FIAh3" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "NCIndex", "Prologues", new { area = "FIANCFIles" }, new { @class = "nav-link FIAp" })</li>
                    <li>@Html.ActionLink("HVIs", "Index", "HVIs", new { area = "FIANCFIles" }, new { @class = "nav-link FIAp" })</li>
                    <li class="drop">
                        @Html.ActionLink("Main Entries", "Main", "Prologues", new { area = "FIANCFiles" }, new { @class = "nav-link FIAp" })
                        <div class="dropdown-content">
                            @Html.ActionLink("Prologue", "Index", "Prologues", new { area = "FIANCFiles" }, new { @class = "nav-link FIAp bg-dark" })
                            @Html.ActionLink("Act 1", "Index", "ActIs", new { area = "FIANCFiles" }, new { @class = "nav-link FIAp bg-dark" })
                            @Html.ActionLink("Interlude", "Index", "Interludes", new { area = "FIANCFiles" }, new { @class = "nav-link FIAp bg-dark" })
                        </div>
                    </li>
                    @{
                        if (isLoggedIn)
                        {
                            <li>@Html.ActionLink("Signout", "Signout", "Users", new { @class = "nav-link FIAp" })</li>
                        }
                    }
                </ul>
            </div>
        </div>
    </nav>
    <h1 class="FIAText FIAh1 center">Night City Files</h1>
    <div class="container body-content">
        @RenderBody()
        <hr class="FIAText" />
        <footer>
            <p class="FIAText">&copy; 2077 - FIA Database</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    @Html.EJS().ScriptManager()
</body>
</html>